<a href="https://colab.research.google.com/github/Rajdegz/Introduction-to-Python/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and its Operations 

In [19]:
import numpy as np
a = np.array([1,2,3]) #This is a 1x3 array. 
print(a)

[1 2 3]


In [35]:
b = np.array([[1,2,3],[4,5,6]]) #This is an example of 2x3 matrix
#print(b)
#print(b.shape)
b[0,0] = 7
print(b)

[[7 2 3]
 [4 5 6]]


In [37]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is an example of square matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
d = np.full((2,2),4)
d

array([[4, 4],
       [4, 4]])

In [43]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [47]:
f = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(f)

[1 5 9]


In [51]:
g = np.empty((0,10))
print(g)

[]


In [50]:
h = np.zeros((2,2))
h

array([[0., 0.],
       [0., 0.]])

In [58]:
e = np.eye(2)
h = np.zeros((2,2))
print(e)
print(h)
print(e+h) #This is the code to get the summation of matrices e and h
print(e-h) #This is the code to get the difference of matrices e and h
print(h-e) #This is the code to get the inverse of the summaation of matrices e and h

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
