<a href="https://colab.research.google.com/github/Rajdegz/Numerical-Methods/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Prelim Exam


In [4]:
import numpy as np

A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print (A)
print (round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5
