<a href="https://colab.research.google.com/github/Rajdegz/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print("Matrix A:")
A = np.array([
     [-5,0],
     [4,1]         
])

B = np.array([
     [6,-3],
     [2,3]
])

print(A)
print("Matrix B:")
print(B)

#For SUM
sum = A+B
print("The sum of Matrix A and B:")
print(sum)
#For Difference1
diff1 = B-A
print("The difference1 of Matrix B and A:")
print(diff1)
#For Difference2
diff2 = A-B
print("The difference2 of Matrix A and B:")
print(diff2)

Matrix A:
[[-5  0]
 [ 4  1]]
Matrix B:
[[ 6 -3]
 [ 2  3]]
The sum of Matrix A and B:
[[ 1 -3]
 [ 6  4]]
The difference1 of Matrix B and A:
[[11 -3]
 [-2  2]]
The difference2 of Matrix A and B:
[[-11   3]
 [  2  -2]]
