<a href="https://colab.research.google.com/github/Rajdegz/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and its Operations


In [1]:
import numpy as np

In [17]:
A = np.array([[-5,0],[4, 1]])
B = np.array([[6,-3],[2,3]])
print("A =",A)
print("B=",B)

A = [[-5  0]
 [ 4  1]]
B= [[ 6 -3]
 [ 2  3]]


In [12]:
#Addition
C = A + B
print(C)

[[ 1 -3]
 [ 6  4]]


In [13]:
#Substraction (B-A)
D = B - A
print(D)

[[11 -3]
 [-2  2]]


In [14]:
#Substraction (A-B)
E = A - B
print(E)

[[-11   3]
 [  2  -2]]
